import { IDeveloper } from "../api/interfaces";

export const developersResponse: IDeveloper[] = [
  {
    rank: 1,
    username: "JanDeDobbeleer",
    name: "Jan De Dobbeleer",
    url: "https://github.com/JanDeDobbeleer",
    avatar: "https://avatars.githubusercontent.com/u/2492783?s=96&v=4",
    since: "monthly",
    popularRepository: {
      repositoryName: "oh-my-posh",
      description: null,
      url: "https://github.com/JanDeDobbeleer/oh-my-posh",
    },
  },
  {
    rank: 2,
    username: "williamboman",
    name: "William Boman",
    url: "https://github.com/williamboman",
    avatar: "https://avatars.githubusercontent.com/u/6705160?s=96&v=4",
    since: "monthly",
    popularRepository: {
      repositoryName: "nvim-lsp-installer",
      description: null,
      url: "https://github.com/williamboman/nvim-lsp-installer",
    },
  },
  {
    rank: 3,
    username: "spydon",
    name: "Lukas Klingsbo",
    url: "https://github.com/spydon",
    avatar: "https://avatars.githubusercontent.com/u/744771?s=96&v=4",
    since: "monthly",
    popularRepository: {
      repositoryName: "flutter_evil_vikings",
      description: "lalala lala",
      url: "https://github.com/spydon/flutter_evil_vikings",
    },
  },
  {
    rank: 4,
    username: "zricethezav",
    name: "Zachary Rice",
    url: "https://github.com/zricethezav",
    avatar: "https://avatars.githubusercontent.com/u/15034943?s=96&v=4",
    since: "monthly",
    popularRepository: {
      repositoryName: "gitleaks",
      description: null,
      url: "https://github.com/zricethezav/gitleaks",
    },
  },
  {
    rank: 5,
    username: "gregberge",
    name: "Greg Bergé",
    url: "https://github.com/gregberge",
    avatar: "https://avatars.githubusercontent.com/u/266302?s=96&v=4",
    since: "monthly",
    popularRepository: {
      repositoryName: "svgr",
      description: null,
      url: "https://github.com/gregberge/svgr",
    },
  },
  {
    rank: 6,
    username: "rom1v",
    name: "Romain Vimont",
    url: "https://github.com/rom1v",
    avatar: "https://avatars.githubusercontent.com/u/543275?s=96&v=4",
    since: "monthly",
    popularRepository: {
      repositoryName: "sndcpy",
      description: null,
      url: "https://github.com/rom1v/sndcpy",
    },
  },
  {
    rank: 7,
    username: "leoluk",
    name: "Leopold Schabel",
    url: "https://github.com/leoluk",
    avatar: "https://avatars.githubusercontent.com/u/859697?s=96&v=4",
    since: "monthly",
    popularRepository: {
      repositoryName: "slack-workspace-sidebar",
      description: null,
      url: "https://github.com/leoluk/slack-workspace-sidebar",
    },
  },
  {
    rank: 8,
    username: "dandavison",
    name: "Dan Davison",
    url: "https://github.com/dandavison",
    avatar: "https://avatars.githubusercontent.com/u/52205?s=96&v=4",
    since: "monthly",
    popularRepository: {
      repositoryName: "delta",
      description: null,
      url: "https://github.com/dandavison/delta",
    },
  },
  {
    rank: 9,
    username: "gakonst",
    name: "Georgios Konstantopoulos",
    url: "https://github.com/gakonst",
    avatar: "https://avatars.githubusercontent.com/u/17802178?s=96&v=4",
    since: "monthly",
    popularRepository: {
      repositoryName: "foundry",
      description: null,
      url: "https://github.com/gakonst/foundry",
    },
  },
  {
    rank: 10,
    username: "shivammathur",
    name: "Shivam Mathur",
    url: "https://github.com/shivammathur",
    avatar: "https://avatars.githubusercontent.com/u/1571086?s=96&v=4",
    since: "monthly",
    popularRepository: {
      repositoryName: "homebrew-php",
      description: null,
      url: "https://github.com/shivammathur/homebrew-php",
    },
  },
  {
    rank: 11,
    username: "toniblyx",
    name: "Toni de la Fuente",
    url: "https://github.com/toniblyx",
    avatar: "https://avatars.githubusercontent.com/u/3985464?s=96&v=4",
    since: "monthly",
    popularRepository: {
      repositoryName: "prowler",
      description: null,
      url: "https://github.com/toniblyx/prowler",
    },
  },
  {
    rank: 12,
    username: "sethvargo",
    name: "Seth Vargo",
    url: "https://github.com/sethvargo",
    avatar: "https://avatars.githubusercontent.com/u/408570?s=96&v=4",
    since: "monthly",
    popularRepository: {
      repositoryName: "go-retry",
      description: null,
      url: "https://github.com/sethvargo/go-retry",
    },
  },
  {
    rank: 13,
    username: "kevinpapst",
    name: "Kevin Papst",
    url: "https://github.com/kevinpapst",
    avatar: "https://avatars.githubusercontent.com/u/533162?s=96&v=4",
    since: "monthly",
    popularRepository: {
      repositoryName: "kimai2",
      description: null,
      url: "https://github.com/kevinpapst/kimai2",
    },
  },
];
