import { IRepository } from "../api/interfaces";
export const repositoriesResponse: IRepository[] = [
  {
    rank: 1,
    username: "TencentARC",
    repositoryName: "GFPGAN",
    url: "https://github.com/TencentARC/GFPGAN",
    description:
      "😏GFPGAN aims at developing Practical Algorithms for Real-world Face Restoration.",
    language: "Python",
    languageColor: "#3572A5",
    totalStars: 6886,
    forks: 944,
    starsSince: 889,
    since: "daily",
    builtBy: [
      {
        username: "xinntao",
        url: "https://github.com/xinntao",
        avatar: "https://avatars.githubusercontent.com/u/17445847?s=40&v=4",
      },
      {
        username: "AK391",
        url: "https://github.com/AK391",
        avatar: "https://avatars.githubusercontent.com/u/81195143?s=40&v=4",
      },
      {
        username: "mdanish-kh",
        url: "https://github.com/mdanish-kh",
        avatar: "https://avatars.githubusercontent.com/u/88161975?s=40&v=4",
      },
      {
        username: "VincentSC",
        url: "https://github.com/VincentSC",
        avatar: "https://avatars.githubusercontent.com/u/5090382?s=40&v=4",
      },
    ],
  },
  {
    rank: 2,
    username: "welk1n",
    repositoryName: "JNDI-Injection-Exploit",
    url: "https://github.com/welk1n/JNDI-Injection-Exploit",
    description:
      "JNDI注入测试工具（A tool which generates JNDI links can start several servers to exploit JNDI Injection vulnerability,like Jackson,Fastjson,etc）",
    language: "Java",
    languageColor: "#b07219",
    totalStars: 1116,
    forks: 269,
    starsSince: 125,
    since: "daily",
    builtBy: [
      {
        username: "welk1n",
        url: "https://github.com/welk1n",
        avatar: "https://avatars.githubusercontent.com/u/24455156?s=40&v=4",
      },
    ],
  },
  {
    rank: 3,
    username: "tangxiaofeng7",
    repositoryName: "CVE-2021-44228-Apache-Log4j-Rce",
    url: "https://github.com/tangxiaofeng7/CVE-2021-44228-Apache-Log4j-Rce",
    description: "Apache Log4j 远程代码执行",
    language: "Java",
    languageColor: "#b07219",
    totalStars: 1652,
    forks: 589,
    starsSince: 454,
    since: "daily",
    builtBy: [
      {
        username: "tangxiaofeng7",
        url: "https://github.com/tangxiaofeng7",
        avatar: "https://avatars.githubusercontent.com/u/45926593?s=40&v=4",
      },
    ],
  },
  {
    rank: 4,
    username: "SeanDaBlack",
    repositoryName: "KelloggBot",
    url: "https://github.com/SeanDaBlack/KelloggBot",
    description: "Kellogg bad | Union good | Support strike funds",
    language: "Python",
    languageColor: "#3572A5",
    totalStars: 254,
    forks: 59,
    starsSince: 86,
    since: "daily",
    builtBy: [
      {
        username: "joeyagreco",
        url: "https://github.com/joeyagreco",
        avatar: "https://avatars.githubusercontent.com/u/57115019?s=40&v=4",
      },
      {
        username: "SeanDaBlack",
        url: "https://github.com/SeanDaBlack",
        avatar: "https://avatars.githubusercontent.com/u/21042399?s=40&v=4",
      },
      {
        username: "Audibles",
        url: "https://github.com/Audibles",
        avatar: "https://avatars.githubusercontent.com/u/13458827?s=40&v=4",
      },
      {
        username: "MeaningOf42",
        url: "https://github.com/MeaningOf42",
        avatar: "https://avatars.githubusercontent.com/u/18193491?s=40&v=4",
      },
      {
        username: "pws1453",
        url: "https://github.com/pws1453",
        avatar: "https://avatars.githubusercontent.com/u/49258062?s=40&v=4",
      },
    ],
  },
  {
    rank: 5,
    username: "feihong-cs",
    repositoryName: "JNDIExploit",
    url: "https://github.com/feihong-cs/JNDIExploit",
    description: "A malicious LDAP server for JNDI injection attacks",
    language: "Java",
    languageColor: "#b07219",
    totalStars: 890,
    forks: 216,
    starsSince: 118,
    since: "daily",
    builtBy: [
      {
        username: "feihong-cs",
        url: "https://github.com/feihong-cs",
        avatar: "https://avatars.githubusercontent.com/u/59082458?s=40&v=4",
      },
    ],
  },
  {
    rank: 6,
    username: "apache",
    repositoryName: "logging-log4j2",
    url: "https://github.com/apache/logging-log4j2",
    description:
      "Apache Log4j 2 is an upgrade to Log4j that provides significant improvements over its predecessor, Log4j 1.x, and provides many of the improvements available in Logback while fixing some inherent problems in Logback's architecture.",
    language: "Java",
    languageColor: "#b07219",
    totalStars: 1769,
    forks: 983,
    starsSince: 102,
    since: "daily",
    builtBy: [
      {
        username: "garydgregory",
        url: "https://github.com/garydgregory",
        avatar: "https://avatars.githubusercontent.com/u/1187639?s=40&v=4",
      },
      {
        username: "remkop",
        url: "https://github.com/remkop",
        avatar: "https://avatars.githubusercontent.com/u/5917763?s=40&v=4",
      },
      {
        username: "rgoers",
        url: "https://github.com/rgoers",
        avatar: "https://avatars.githubusercontent.com/u/120415?s=40&v=4",
      },
      {
        username: "jvz",
        url: "https://github.com/jvz",
        avatar: "https://avatars.githubusercontent.com/u/791275?s=40&v=4",
      },
      {
        username: "mikaelstaldal",
        url: "https://github.com/mikaelstaldal",
        avatar: "https://avatars.githubusercontent.com/u/716104?s=40&v=4",
      },
    ],
  },
  {
    rank: 7,
    username: "mpcabete",
    repositoryName: "bombcrypto-bot",
    url: "https://github.com/mpcabete/bombcrypto-bot",
    description:
      "This is a python bot that automatically logs in, clicks the new button, and sends heroes to work in the bombcrypto game. It is fully open source and free.",
    language: "Python",
    languageColor: "#3572A5",
    totalStars: 348,
    forks: 207,
    starsSince: 12,
    since: "daily",
    builtBy: [
      {
        username: "mpcabete",
        url: "https://github.com/mpcabete",
        avatar: "https://avatars.githubusercontent.com/u/69962256?s=40&v=4",
      },
      {
        username: "cristhianbreunig",
        url: "https://github.com/cristhianbreunig",
        avatar: "https://avatars.githubusercontent.com/u/38818343?s=40&v=4",
      },
      {
        username: "newerton",
        url: "https://github.com/newerton",
        avatar: "https://avatars.githubusercontent.com/u/4175945?s=40&v=4",
      },
      {
        username: "marcellosso",
        url: "https://github.com/marcellosso",
        avatar: "https://avatars.githubusercontent.com/u/47645704?s=40&v=4",
      },
      {
        username: "Rout222",
        url: "https://github.com/Rout222",
        avatar: "https://avatars.githubusercontent.com/u/4533667?s=40&v=4",
      },
    ],
  },
  {
    rank: 8,
    username: "cilium",
    repositoryName: "cilium",
    url: "https://github.com/cilium/cilium",
    description: "eBPF-based Networking, Security, and Observability",
    language: "Go",
    languageColor: "#00ADD8",
    totalStars: 9996,
    forks: 1264,
    starsSince: 78,
    since: "daily",
    builtBy: [
      {
        username: "aanm",
        url: "https://github.com/aanm",
        avatar: "https://avatars.githubusercontent.com/u/5714066?s=40&v=4",
      },
      {
        username: "tgraf",
        url: "https://github.com/tgraf",
        avatar: "https://avatars.githubusercontent.com/u/1417913?s=40&v=4",
      },
      {
        username: "joestringer",
        url: "https://github.com/joestringer",
        avatar: "https://avatars.githubusercontent.com/u/1243336?s=40&v=4",
      },
      {
        username: "ianvernon",
        url: "https://github.com/ianvernon",
        avatar: "https://avatars.githubusercontent.com/u/3858271?s=40&v=4",
      },
      {
        username: "brb",
        url: "https://github.com/brb",
        avatar: "https://avatars.githubusercontent.com/u/122571?s=40&v=4",
      },
    ],
  },
  {
    rank: 9,
    username: "vercel",
    repositoryName: "turborepo",
    url: "https://github.com/vercel/turborepo",
    description:
      "The High-performance Build System for JavaScript & TypeScript Codebases",
    language: "Go",
    languageColor: "#00ADD8",
    totalStars: 2115,
    forks: 54,
    starsSince: 380,
    since: "daily",
    builtBy: [
      {
        username: "jaredpalmer",
        url: "https://github.com/jaredpalmer",
        avatar: "https://avatars.githubusercontent.com/u/4060187?s=40&v=4",
      },
      {
        username: "molebox",
        url: "https://github.com/molebox",
        avatar: "https://avatars.githubusercontent.com/u/22930449?s=40&v=4",
      },
      {
        username: "KarelVerschraegen",
        url: "https://github.com/KarelVerschraegen",
        avatar: "https://avatars.githubusercontent.com/u/11301291?s=40&v=4",
      },
      {
        username: "becca",
        url: "https://github.com/becca",
        avatar: "https://avatars.githubusercontent.com/u/23545426?s=40&v=4",
      },
      {
        username: "gaspar09",
        url: "https://github.com/gaspar09",
        avatar: "https://avatars.githubusercontent.com/u/5875536?s=40&v=4",
      },
    ],
  },
  {
    rank: 10,
    username: "sxyu",
    repositoryName: "svox2",
    url: "https://github.com/sxyu/svox2",
    description:
      "Plenoxels: Radiance Fields without Neural Networks, Code release WIP",
    language: "Python",
    languageColor: "#3572A5",
    totalStars: 257,
    forks: 15,
    starsSince: 55,
    since: "daily",
    builtBy: [
      {
        username: "sxyu",
        url: "https://github.com/sxyu",
        avatar: "https://avatars.githubusercontent.com/u/16251946?s=40&v=4",
      },
      {
        username: "sarafridov",
        url: "https://github.com/sarafridov",
        avatar: "https://avatars.githubusercontent.com/u/16036159?s=40&v=4",
      },
    ],
  },
  {
    rank: 13,
    username: "christophetd",
    repositoryName: "log4shell-vulnerable-app",
    url: "https://github.com/christophetd/log4shell-vulnerable-app",
    description:
      "Spring Boot web application vulnerable to CVE-2021-44228, nicknamed Log4Shell.",
    language: "Java",
    languageColor: "#b07219",
    totalStars: 305,
    forks: 85,
    starsSince: 126,
    since: "daily",
    builtBy: [
      {
        username: "christophetd",
        url: "https://github.com/christophetd",
        avatar: "https://avatars.githubusercontent.com/u/136675?s=40&v=4",
      },
      {
        username: "rayhan0x01",
        url: "https://github.com/rayhan0x01",
        avatar: "https://avatars.githubusercontent.com/u/47485393?s=40&v=4",
      },
    ],
  },
];
